# Generated by Django 4.2.16 on 2024-12-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensaKata_App', '0018_userprogress_delete_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='daily_challenges_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='daily_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='daily_words_learned',
            field=models.IntegerField(default=0),
        ),
    ]
