# Generated by Django 4.2.16 on 2024-12-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LensaKata_App', '0012_userscore_delete_userstatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
