# Generated by Django 4.2.16 on 2024-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensaKata_App', '0019_userprogress_daily_challenges_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paketlangganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='Aktif', max_length=20)),
            ],
        ),
    ]
