# Generated by Django 4.2.16 on 2024-12-15 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LensaKata_App', '0025_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='kursus_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_video', models.CharField(max_length=255)),
                ('deskripsi_video', models.TextField()),
                ('video_url', models.URLField()),
                ('durasi', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_details', to='LensaKata_App.kursus')),
            ],
        ),
    ]
