# Generated by Django 5.1.3 on 2024-11-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langganan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='langganan',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
