# Generated by Django 5.1.3 on 2024-11-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langganan', '0002_langganan_is_premium'),
    ]

    operations = [
    ]
