# Generated by Django 4.2.16 on 2024-11-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LensaKata_App', '0003_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewCard',
        ),
    ]
