# Generated by Django 4.2.16 on 2024-12-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensaKata_App', '0020_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
