# Generated by Django 4.2.16 on 2024-12-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LensaKata_App', '0021_subscription_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='months',
        ),
    ]
