# Generated by Django 4.2.16 on 2024-12-14 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSPOKSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_sentence', models.CharField(max_length=300)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('predicate', models.CharField(blank=True, max_length=100)),
                ('object', models.CharField(blank=True, max_length=100)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
