# Generated by Django 4.2.16 on 2024-11-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LensaKata_App', '0007_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
