# Generated by Django 4.2.16 on 2024-12-14 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LensaKata_App', '0023_storyrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPOKChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(help_text='Masukkan kalimat lengkap untuk tantangan', max_length=255)),
                ('subject', models.CharField(help_text='Jawaban untuk Subjek', max_length=100)),
                ('predicate', models.CharField(help_text='Jawaban untuk Predikat', max_length=100)),
                ('object', models.CharField(help_text='Jawaban untuk Objek', max_length=100)),
                ('description', models.CharField(help_text='Jawaban untuk Keterangan', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SPOKSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LensaKata_App.spokchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
